import gleam/io
import gleam/string
import simplifile
import tom

const core = "../core/"

pub fn main() {
  let assert Ok(toml) = simplifile.read(from: core <> "gleam.toml")
  let assert Ok(toml) = tom.parse(toml)
  let version = case toml |> tom.get_string(["version"]) {
    Ok(version) -> version
    Error(_) -> "dev"
  }

  let assert Ok(_) = simplifile.create_directory_all(core <> "src/generated/")

  let contents =
    [
      "// This file was generated by scopa/dev/scripts/generate_version",
      "// You typically do not need to edit this file",
      "pub const version = \"" <> version <> "\"",
    ]
    |> string.join("\n")

  let assert Ok(_) =
    simplifile.write(to: core <> "src/generated/version.gleam", contents:)

  io.println("Version generated: " <> version)
}
