name = "scopa"
version = "3.0.0"
# description = ""
# licences = ["Apache-2.0"]
# repository = { type = "github", user = "", repo = "" }
# links = [{ title = "Website", href = "" }]
#
# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

[dependencies]
lustre = ">= 5.6.0 and < 6.0.0"
gleam_stdlib = ">= 0.71.0 and < 1.0.0"

[dev_dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
lustre_dev_tools = ">= 2.3.6 and < 3.0.0"

[tools.lustre.html]
stylesheets = [
  { href = "/css/style.css" },
  { href = "/css/setup.css" },
  { href = "/css/team_names_editor.css"}
]

[tools.lustre.build]
minify = true
