import gleam/string
import gleeunit
import gleeunit/should

import scripts/generate_version

pub fn main() -> Nil {
  gleeunit.main()
}

pub fn generate_version_file_content_test() {
  let toml = "version = \"1.2.3\""
  let expected =
    "// This file was generated by scopa/dev/scripts/generate_version\n"
    <> "// You typically do not need to edit this file\n"
    <> "pub const version = \"1.2.3\""

  generate_version.generate_version_file_content(toml)
  |> should.equal(expected)
}

pub fn generate_default_version_test() {
  let toml = ""
  generate_version.generate_version_file_content(toml)
  |> string.contains("pub const version = \"dev\"")
  |> should.be_true()
}
