name = "scopa"
version = "3.0.0"
description = "A scoring app for the Italian card game Scopa"
licences = ["BSD-3-Clause"]
repository = { type = "github", user = "nigeleke", repo = "scopa" }
links = [{ title = "Website", href = "https://nigeleke.github.io/scopa/" }]

[dependencies]
lustre = ">= 5.6.0 and < 6.0.0"
gleam_stdlib = ">= 0.71.0 and < 1.0.0"
varasto = ">= 4.0.0 and < 5.0.0"
gleam_json = ">= 3.1.0 and < 4.0.0"

[dev_dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
lustre_dev_tools = ">= 2.3.6 and < 3.0.0"

[tools.lustre.html]
stylesheets = [
  { href = "/css/style.css" },
  { href = "/css/glow.css" },
  { href = "/css/tally_editor.css"},
  { href = "/css/target.css"},
  { href = "/css/team_name.css"},
  { href = "/css/team_names_editor.css"},
  { href = "/css/scopa_editor.css"},
  { href = "/css/setup.css" },
  { href = "/css/in_progress.css" },
  { href = "/css/completed.css" },
]

[tools.lustre.build]
minify = true
