# Quick feedback for unit tests on non-main commits.
#
name: Commit Cycle

on: push

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Compile
              run: |
                  cargo install cargo-binstall
                  cargo binstall dioxus-cli
                  dx build

            - name: Lint
              run: cargo clippy

            - name: Test
              run: cargo test
