name: Release

on:
    push:
        tags:
            - "v*.*.*"

jobs:
    tags:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - uses: nigeleke/github/.github/actions/cargo-verify-version-vs-tag@main
            - shell: bash
              run: |
                  echo "checkout"
                  git status

    bundle:
        needs: [tags]
        uses: nigeleke/github/.github/workflows/dioxus-bundle.yml@main
        with:
            platform: web

    publish-docker-image:
        needs: [bundle]
        runs-on: ubuntu-latest
        env:
            DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
            DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        steps:
            - uses: nigeleke/github/.github/actions/rust-setup@main
            - shell: bash
              run: |
                  echo "rust setup"
                  git status
            - uses: nigeleke/github/.github/actions/dockerhub-publish@main
              with:
                  platforms: linux/amd64,linux/arm64
                  tags: nigeleke/scopa:latest,nigeleke/scopa:${{ github.sha }}
            - shell: bash
              run: |
                  echo "dockerhub publish"
                  git status

    publish-site:
        needs: [bundle]
        uses: nigeleke/github/.github/workflows/rust-publish.yml@main
        secrets: inherit
